language: python
#version
python:
  - "3.6"
cache: pip

install:
  - pip install --upgrade
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE mydiary_pro;" -U postgres

script:
  - nosetests --with-coverage
after_success:
  - coveralls
